{ +block{cjx-annoyance} }
/wiseatom/banner/pack_
-bobo_recommend_
/3dmgamegzh\.png
=mumumoniqi-piaochuang-
/dongaogg/.*
/live800\.
/loooyu\.js
/shenmago_download_app_
/source/plugin/yw_alertlogin/.*
/tb/_/video_frs_head_
/tencentvideo/script/webtips/.*
/tianya_recommend\?
/to8to_pc/chunks/slide_and_popup_
/wp-content/plugins/upprev/.*
/yksmartbanner\.
/z\.zolapp\.
=Ad_ZPlusGoods&
.cir-smart\.baidu\.com[/&:?=_]
.crs\.baidu\.com[/&:?=_]
.goutong\.baidu\.com[/&:?=_]
.ntalker\.com[/&:?=_]
.wpa\.b\.qq\.com/cgi/wpa\.php\?
.025yimei\.com/templets/default/js/swt\.js
.100xuexi\.com/CssModel/botad\.js
.115img\.com/static/pc/d_
.126\.net/caipiao/js2/dialog\.js
.126\.net/caipiao/js2/index/homePop\.js
.163\.com/special/.*/bobo\.html
.163\.com[/&:?=_].*/boboData
.17173\.com/actapi/qiyu/
.17173cdn\.com[/&:?=_].*/js/task/src/task/live/greenhand/
.21sq\.org/js/downloadbanner\.js
.360doc\.com/js/index7/mask_index_yc\.js
.39\.net/PictureLib/A/f76/20160825/org_749281\.png
.51credit\.com/bbs/js/bbs-end-layer\.js
.51cto\.com/iframe/get-station-ads
.51liucheng\.com/js/dialogLogin\.js
.51zxw\.net/netclass/images/.*_top\.jpg
.6pan\.cc/ps/vip\.jpg
.ad\.qn\.img-space\.com[/&:?=_]
.ali213\.net/js/3g/newsdetail\.js
.alicdn\.com/mtb/lib-smartbanner-
.aoji\.cn/default/looyu/
.asp300\.com/2017images/kefu\.js
.autohome\.com\.cn/vr/.*\?pvareaid=
.autoimg\.cn/Space/help/HelpRdTask\.js
.baidu\.com/cms/lemmaconfig/baikeDynamic\.
.baidu\.com/cms/lemmaconfig/navbarAd\.
.baidu\.com[/&:?=_].*/app/banner_
.baidu\.dj/u/upan/you\.html
.baike\.com/newtop/news\.html
.bdstatic\.com/searchbox/icms/searchbox/img/.*\.jpg
.bdstatic\.com/tb/img/icon_coo_operation_
.bendibao\.com/weixin_
.bestpush\.pconline\.com\.cn[/&:?=_]
.betteredu\.net/js/pop_tuiguang_
.bilibili\.com/html/ads-index\.js
.bjsxt\.com/statics/js/bjsxt/js\.js
.bjwj2y\.com/JS/LsJS\.aspx
.blog\.sina\.com\.cn/lm/mini/
.bobo\.com/special/mod-follow/
.c-ctrip\.com/ResUnionOnline/R3/float/floating_normal\.min\.js
.caixin\.com/file/content/js/mobile_news_app_banner\.js
.cctvpic\.com/photoAlbum/templet/common/.*/game_
.chazidian\.com/all/gg_
.china\.com/images/milapp
.chinaacc\.com/lamu/piao
.chinacloudsites\.cn/api/promotion\?
.chinanews\.com/fileftp/2016/06/2016-06-13/U194P4T47D35171F967DT20160613093733\.jpg
.chinanews\.com/fileftp/2016/08/2016-08-04/U194P4T47D36220F967DT20160804155100\.jpg
.chinatimes\.com/ads/
.cndns\.com/incs/js/website_mobile\.js
.con-article\.hjapi\.com/v1/txs/
.cpu\.baidu\.com[/&:?=_]
.ctfile\.com/img/.*ssp
.daf-rs\.com/imageViewer/wpAd
.dahe\.cn/indiboy/ads/
.dangbei\.net/img/db/downdangbei\.gif
.dilidili\.wang/uploads/allimg/171227/1_1520203421\.png
.dmzj\.com/module/js/float_code\.js
.dmzj\.com/public/js/app_banner\.js
.docin\.com/building/getAdvById\.
.douyu\.com/dygev/.*\.swf
.duba\.net/skins/2009/images/db300_250\.gif
.dwstatic\.com[/&:?=_].*/newsPopup/
.dwstatic\.com[/&:?=_].*/sidebar\.js
.easteat\.com/templets/default/images/media-top\.png
.eastmoney\.com/Extends/GetReferralLinkJavaScriptObj
.eastmoney\.com/js/.*Share\.js
.eastmoney\.com/public/ad\.tools\.
.eic\.org\.cn/api/Popup\?
.eic\.org\.cn[/&:?=_].*/analytics
.enet\.com\.cn/counter\.php
.ettoday\.net/style/mobileweb2014/js/smartbanner/jquery\.smartbanner\.
.ettoday\.net/style/video-ad/
.fengbuy\.com/recommend-new\.
.fh21\.com\.cn/js/passport/createQuickMenu\.js
.forex\.com\.cn/index\.php/Invoking/tanchukuang
.forex\.com\.cn/statics/images/ewm\.jpg
.fydisk\.com/images/showvip\.gif
.goodcome\.com\.tw/block/ad/rndtopad\.php
.gtimg\.com/finance/js/st/p/news_ad_
.gtimg\.com/gamezone/2014index/images/600x75\.jpg
.gtimg\.com/pingjs/ext2020/dc2017/dist/m_tips/tips\.js
.gz-chengkao\.com/js/duo\.js
.hahamx\.cn/images/banner/
.hanjutv\.com/public/js/layer/layer\.js
.hao123img\.com/v4/MB/xU/jy/VY/YX/MBxUjyVYYX\.js
.heiguang\.com/_r/2015/js/hrBottomBar\.
.hexun\.com/2016/pc/618\.swf
.hexun\.com/2017-11-07/191534592\.jpg
.hexun\.com/inc/popbox\.aspx
.hexun\.com[/&:?=_].*/appDplus
.hjapi\.com/v1/pageSoftText\?
.hjfile\.cn/lib/hui/footer/0\.1\.0/footer\.js
.hjfile\.cn/lib/uzhi/uzt\.
.hjfile\.cn/site/hj-lzs/
.hjfile\.cn/site/js/pop_gift_plugin\.js
.house365\.com/js/fixWin\.php
.howbuy\.com/subject/js/jquery\.blockUI\.js
.howbuy\.com/subject/js/layer/layer\.js
.hujiang\.com/Web/tx\.ashx
.iask\.sina\.com\.cn/s-b/mxbg
.iciba\.com/static/images/download_banner\.png
.ifeng\.com/uploadfiles/main_blog/main_child/v3_block
.ifengimg\.com/auto/js/.*enquiry
.ifengimg\.com[/&:?=_].*/red2018icon\.
.igo\.cn/liuxue/js/slideBar
.imall\.cctv\.com[/&:?=_]
.imall\.cntv\.cn[/&:?=_]
.ithome\.com/images/productgif/pcmaster\.gif
.ithome\.com/images/v2\.1/downsoftmaster\.gif
.jc001\.cn/img/yhj\.gif
.jc001\.cn/indexnew/js/yuyue\.js
.jia\.com/js/common/jia-common\.js
.jia\.com/js/tuku/footBanner_
.jia\.com/js/zixun/news\.js
.jia\.com/js/zixun/zixun_
.jianshe99\.com/lamu/
.kaoyan\.com/__pub/shop_book\.html
.kaoyan\.com/global/js/backtopnew\.js
.kaoyan\.com/school/final_class\.html
.kaoyan\.com/school/js/yz\.school\.packed\.js
.kekenet\.com/images/.*/app
.kgimg\.com/public/root//images/hardware\.jpg
.kongzhong\.com/style/newindex/js/tad\.js
.koolearn\.com/v2/js/.*AD\.js
.koolearn\.com/v2/js/wxewm\.js
.koolearn\.com/www/subject/script/subject_form\.js
.kuakao\.com:6053/floatcard\?
.kuwo\.cn/static/swf/xctg\.swf
.lofter\.com/blogPhotoAd\?
.lofter\.com/mailEntry\.do\?blogad
.longzhu\.com/i/api/videos/dailyRecommend\?
.me360\.com/swt/swt\.js
.meilele\.com/js/mll/baiduLabelRecommend\.
.mianwww\.com/wp-content/uploads/2014/05/insigmaedu1\.gif
.mitbbs\.com/img/app
.mnks\.cn/jk/appAD_
.mtime\.cn/library/.*/ECommerce/GoodsAndFeatureCtrl\.js
.naajie\.com/float\.js
.netease\.com/f2e/auto/modules/float-ask-price/
.netease\.com/fz/interface/frontend/fz\.do\?pos=tongyong-
.netease\.com[/&:?=_].*bobologo
.neuralstemcell\.com\.cn/img/js\.js
.ntce\.com/images/js/ntce_public\.js
.offcn\.com/index\.php\?m=dbsource&c=call&a=get&id=75
.offcn\.com/offcnewm/
.ol-img\.com/channel/tuku/js/tukuPopup\.js
.pcauto\.com\.cn/forum/1508/intf7631\.js
.pcauto\.com\.cn/forum/autobbs/clubtl/
.pchome\.com\.tw/js/fancybox/
.pconline\.com\.cn/intf/hot_
.pinggu\.org/api/bbsgg\.
.pstatp\.com/growth/mobile_list/image/bonus_
.pstatp\.com[/&:?=_].*/bannersdk/
.qhimg\.com/static/5dcd236fc857be9c,5b391c33a0748022\.js
.qidian\.com/Images/990x40_
.qudao\.com/common/minisite\.js
.qyer\.com/qcross/home/ajax\?action=banner
.qyerstatic\.com/common/models/common/component/footerBanner/
.rjzxw\.com/temp/index\.files/logo2\.gif
.rrjc\.com/home/seo/ad/
.shejiben\.com/common/libs/layer\.js
.shejiben\.com/common/widgets/ui/.*zb\.js
.shopping\.udn\.com/mall/cus/cat/OutWebAd\.do\?
.showguide\.cn/templets/.*/qqcenter\.js
.showguide\.cn/templets/.*/sg-ad\.js
.sina\.com\.cn/1016/getPhones-
.sina\.com\.cn[/&:?=_].*/energypop\.
.sinaimg\.cn/finance/.*/hqMainTopBanner\.js
.sinaimg\.cn/finance/.*/sideQR
.sinaimg\.cn/finance/app2018/js/appbar\.js
.sinaimg\.cn/finance/hq_finapp_ad/
.sinaimg\.cn/finance/ny_live.*\.js
.sinaimg\.cn/finance/wanghong_
.sinaimg\.cn/large/a518ed97jw1eu4mxubbe6j209q01e3ys\.jpg
.sinaimg\.cn/mw690/005uyUwYjw1eocc98cbgag30gk02ygm9\.gif
.sinaimg\.cn/tech/.*/sidebar\.js
.sinaimg\.cn[/&:?=_].*/everyoneReading\.js
.soft4fun\.net/wp-content/themes/arthemia/js/common_footer_min\.js
.soso\.com/wenwen/i/ad/
.soufunimg\.com/common_m/m_public/js/wa
.sp\.qf\.56\.com[/&:?=_]
.taobao\.com/api/data/v2/d9543feac7c9433a98bc85be3ba856b1\.js
.taobao\.com/js/smartbanner/
.tfg2\.com/images/upfile/banner/
.tianya\.cn/shang/.*/index\.shtml
.tianyaui\.com/cms_fragments/res/.*/bbs_include_mod\.js
.tianyaui\.com/global/dashang/vip_seat/js/ds_vip_seat\.js
.to8to\.com/assets/wap//common/widgets/appGuide/appGuide\.
.to8to\.com/yezhu/zxbjWidget\.
.to8to\.com[/&:?=_].*_bottom_
.toutiao\.haotui\.com/data/js/0\.js
.tq\.cn/floatcard\?
.tsdmw\.net/img01/MP3/pm_
.tuyiyi\.com/tuyiyi/m\.js
.tv002\.com/img/down1_ssp1\.gif
.upaiyun\.com/wp-content/uploads/2016/12/wenzhangyouce
.w3cschool\.cn/attachments/image/20170919/1505817817281252\.jpg
.wanwan\.sina\.com\.cn/kb/
.wanwan\.sina\.com\.cn/sinasupersport/back/
.wbiao\.cn/common/adapi/
.wbiao\.cn/common/newsbannerAds/
.wbiao\.co/src2/js/expand/fudong/
.webservice\.360doc\.com[/&:?=_]
.wingontravel\.com/Static/headerfooter/Content/js/masterpage\.
.wumii\.cn/ext/relatedItemsWidget
.wuxibus\.com/Image/title
.xcar\.com\.cn/bbs/adfocus\.js
.xiaoma\.com/kf\.php\?arg=
.xiaoma\.com/xiaoma/www/js/article_right
.xnimg\.cn[/&:?=_].*/liveinc/rightlive\.js
.ye120\.com/swt\.js
.ye120\.com/zool\.js
.youdao\.com/market/banner/banner
.youdao\.com/www/banner\.html
.yytcdn\.com/js/common/widget/pcpusher\.
.zhiyoo\.com/mplus/images/banner\.jpg
.zndsssp\.dangbei\.net[/&:?=_]
.zol-img\.com\.cn/star/image/star-banner2\.gif
.zol\.com/index\.php\?c=ZolShopIndex
.zp365\.com/newhousered/hb-index-pop-
.zuoyebang\.cc/static/question/question/resource/QRCode_
.zuoyebang\.cc/zyb_4953cbb8a9a2332469592196c056a906\.jpg
.yuedu\.baidu\.com/hybrid/wkrec/search\?
.zhan\.com[/&:?=_].*/middle_ad_modal\.js
.dealmoon\.com/build/js/www/home/activity-pop/index\.
.zglww\.net/jsnew/pfkf\.js
.ld0766\.com/index\.php\?m=call&id=10
.sina\.com\.cn/other/src/app/SFANewVersionPop\.js
.qq\.com/inc/utf8/nav/ad\.htm
.gtimg\.com/finance/js/st/p/cms/ce56e2f3303d17b6\.js
.gtimg\.com/finance/js/st/p/quotpage/maxcard_
.med66\.com/lamu/
.51cto\.com/edu/blog/.*box\.js
.taisha\.org/statics/js/pc2\.0/common/form\.bottom\.
.autoimg\.cn/club/v1Content/images/heycar
.china\.cn/js/common/daniel_pop/
.chinaacc\.com/lamu/.*dl-
.chinaacc\.com/lamu/.*piao
.xhd\.cn/topic/leyu-piaofu/
.zol\.com\.cn/index\.php\?c=Api_JumpApi&
.jjwxc\.net/adsmanage\.
.sinaimg\.cn/tech/zcapp2018/zcapp\.js
.233\.com/js/side\.htm
.soufunimg\.com/homepage/new/.*/buttomLayer\.js
.vuetifyjs\.com/notify\.json
.qhres\.com/static/b4f92ac067a4768b/v4/modules/footer\.js
.daniujiaoyu\.com/js/zk
.daniuxuexiao\.org\.cn/js/zk
.weiyun\.com/proxy/domain/boss\.qzone\.qq\.com/fcg-bin/fcg_get_multiple_strategy\?
.aoji\.cn/static/js/pushadv\.js
.aoji\.cn/static/js/yiliao/ad_common\.js
.zx123\.cn/templates/zx123cs/theme-2015/js/right_xh\.js
.people\.com\.cn/rmrb/tplimg/new\.js
.appledaily\.hk/banners/subscription/
.bilibili\.com/x/web-interface/archive/special/recommend\?aid=
.lancdn\.com/tmp3/GG_Notice\.png
.chinaacc\.com/upload/.*zhongjizhicheng
.zhangzishi\.cc/cdn-cgi/apps/
.macx\.cn/js/blockadblock\.js
.bestqikan\.com/static/js/swt\.js
.book118\.com/Public/book118/js/side-customer/customer\.js
.51cto\.com/js/activity_pop\.js
.kuakao\.com/index\.php\?m=content&c=index&a=show_ad
.qinxue100\.com/qinxue/pc/js/add_js\.js
.hujiang\.com/ciku/getDetailSoftText/
.hujiang\.com/ciku/getLesson
.zbcdn\.net/__uvjgyw/slb\.default\.js
.sina\.com\.cn/other/src/sfc_app_sidebar\.js
.sinaimg\.cn/cj/finance/forex/res/searchCallup\.js
.tsdm\.live/weibo\.html
.28\.com/public/js/w3c_float\.js
.chinaacc\.com/upload/js/cia_mjy_pf/
.kmf\.com/da/do
.daiyanbao\.com/flash/md
.banzou\.name/qq/qq2\.js
.5888\.tv/Js/topBanner\.js
.dfcfw\.com/zndh/
.jsdelivr\.net/npm/live2d-
.51offer\.com/mod/public/talk/
.51offer\.com/pageData/getDataByModuleIdandKey\.html\?leadkey=adList&
.chinalawedu\.com/js/weixin/weixin\.js
.chinalawedu\.com/js/zxkf\.js
.baidu\.com/xpage/form/getform\?id=wk_pc_skin
.bdimg\.com[/&:?=_].*/popOperationView_.*\.js
.aixifan\.com/static/.*/appGuide/
.icourse163\.org/dwr/call/plaincall/CommonBean\.obtain\.dwr
.3158\.cn/min/webim\.
.3158\.cn/static/js/fixbtm/
.house365\.com/im_show/imshow\.js
.qixin007\.com/webbanner/
.3158\.cn[/&:?=_].*_analyser\.
/cp2\.gif\?.*=qc_
/hunter/alog/.*
/js/soku-analytics\.js
/scriptonline\.js\?uin=
/soku/giantstar/js/youlog\.js
/tb/img/hg/hg\.gif\?
/v\.gif\?logtype=
/yesky/js/counter/.*
/zcool-analytics\.js
.syzjxz2018\.cn[/&:?=_]
.gog\.cn/sys/online_calc\.js
.dhgxl8qk9zgzr\.cloudfront\.net/js/log\.js
.126\.net[/&:?=_].*analysis
.zol\.com\.cn/pvn/
.laosiji\.com/static/js/lib/od_statistics\.js
.100bt\.com/dc\?Url
.113\.105\.248\.169[/&:?=_]
.115img\.com/static/115tj\.js
.123cha\.com/counter\.js
.218\.30\.15\.193/phpstat/count/
.28\.com/count\.js
.28\.com/countnew\.js
.39\.net/js/wt\.js
.5173\.com/__tra\.gif\?
.58cdn\.com\.cn/resource/xxzl/xxfw/
.8cnd\.com[/&:?=_]
.91160\.com/nykj/f=static/v4/common/tj\.js
.a-m-s\.adnonstop\.com[/&:?=_]
.a\.tbcdn\.cn/s/ac\.js
.a\.tbcdn\.cn/s/atp\.js
.a\.tbcdn\.cn/s/tb-tracer-min\.js
.abab\.com/pv\.js
.acookie\..*\.gif\?
.agrantsem\.com/js/ag\.js
.analy\.tuniu\.cn[/&:?=_]
.analyse\.weather\.com\.cn[/&:?=_]
.analysis\.chinaiiss\.com[/&:?=_]
.analytics-union\.sandai\.net[/&:?=_]
.analytics-union\.xunlei\.com[/&:?=_]
.analytics\.21cn\.com[/&:?=_]
.analytics\.oneplus\.cn[/&:?=_]
.analytics\.techweb\.com\.cn[/&:?=_]
.analytics\.tv189\.cn[/&:?=_]
.api\.cupid\.qiyi\.com/etx\?
.api\.cupid\.qiyi\.com/track2
.apistat\.gao7\.com[/&:?=_]
.apistat\.wasu\.cn[/&:?=_]
.apple\.www\.letv\.com/env/\?
.ark\.letv\.com/t\?
.autohome\.com\.cn/risk_fp_log\?
.autoimg\.cn/bi/mda/ahas_body\.
.baidu\.com/4\.gif\?
.baidu\.com/smalllog/
.baidu\.com[/&:?=_].*/w\.gif\?
.bc\.qunar\.com[/&:?=_]
.bdstatic\.eastmoney\.com[/&:?=_]
.bendibao\.com/js/count\.js
.bitauto\.com/bglog\.gif\?
.bshare\.cn/bshare_view\?Callback=
.bt\.ktxp\.com/iframe/statistics\.js
.btdb\.in/beacon\.html
.btime\.com/api/weblog\?
.bytecdn\.cn/ta/resource/v0/analytics\.js
.ca\.cbsi\.com\.cn/rpv\?
.carstat\.bitauto\.com[/&:?=_]
.cbjg\.cqnews\.net[/&:?=_]
.cbsi\.com\.cn/js/mlt\.js
.ccoo\.cn/mystat\.asp
.cdnlog\.zhenai\.com[/&:?=_]
.cheshi-img\.com/js/pv\.min\.js
.chinatimes\.com/analytics/
.chouti\.com/js/tingyun-rum\.js
.cjyun\.org/assets/js/analytics\.js
.click\.tianyaui\.com[/&:?=_]
.cnfol\.com/Count\.html
.cnmo\.com/pv\.js
.cnpc\.infzm\.com[/&:?=_]
.comm100\.cn/livechatserver/chatbutton\..*&res=
.count\.candou\.com[/&:?=_]
.count\.enet\.com\.cn[/&:?=_]
.count\.iyaxin\.com[/&:?=_]
.count\.pcauto\.com\.cn[/&:?=_]
.count\.pcgames\.com\.cn[/&:?=_]
.counter\.pcauto\.com\.cn[/&:?=_]
.counter\.tianjimedia\.com[/&:?=_]
.countpage\.sznews\.com[/&:?=_]
.cpms\.now\.com[/&:?=_]
.damai\.cn/phpstat/
.data\.xici\.net[/&:?=_]
.dcs\.conac\.cn/js/
.dfcfw\.com/libs/js/counter\.js
.dianping\.com/hippo\.gif\?
.dig\.qbao\.com[/&:?=_]
.doc88\.com[/&:?=_].*/count\.js
.dp3\.qq\.com/qqcom/
.duba\.com/static/.*/js/min\.pop\.js
.dw\.xcar\.com\.cn[/&:?=_].*\.gif\?
.ea3w\.com/pv\.js
.eastmoney\.com/analysis/
.ejieban\.com[/&:?=_]
.fcm\.baidu\.com[/&:?=_]
.fengniao\.com.*/pv\.js
.fjsen\.com:81/mysql/count/
.frame\.enet\.com\.cn/a\.php
.fx678\.com/htcount/count\.js
.g\.yccdn\.com[/&:?=_]
.gridsumdissector\.cn/gs\.gif\?
.guahao\.cn/blank\.gif\?
.hao123img\.com/res/js/track\.js
.haostat\.qihoo\.com[/&:?=_]
.hc360\.com/js/module/common/logrecordservice\.
.hdslb\.com/js/bfd\.js
.hexun\.com/js/att_count\.js
.hm\.baidu\.com/mkt\.js
.hupu\.com/_dace\.gif\?
.house365\.com/js/analyze\.js
.hz\.youku\.com/red/
.iciba\.com/web/static/scripts/kds2_record\.js
.icon\.zol-img\.com\.cn/mainpage/js/click\.js
.ifengimg\.com[/&:?=_].*/sta_collection
.img\.kuai\.xunlei\.com/js/statistics\.js
.imgstat\.baidu\.com[/&:?=_]
.imp\.zol\.com\.cn[/&:?=_]
.iqiyi\.com/etx\?
.iqiyi\.com/js/pingback/
.iqiyi\.com/track
.isdspeed\.qq\.com[/&:?=_]
.it168\.com/pv\.js
.itc\.cn/cache/lib/v2/odvmonitor/
.itc\.cn/hdpv\.js
.itc\.cn/pv/
.itc\.cn[/&:?=_].*/tracker\.js
.js\.passport\.qihucdn\.com/11\.0\.1\.js
.kaipuyun\.cn/count/
.kkpgv2\.xunlei\.com[/&:?=_]
.l\.ykimg\.com[/&:?=_]
.ll\.hudong\.com[/&:?=_]
.log\.daqi\.com[/&:?=_]
.log\.mtime\.cn[/&:?=_]
.log\.music\.baidu\.com[/&:?=_]
.log\.vdisk\.cn[/&:?=_]
.log\.zongheng\.com[/&:?=_]
.log2\.mtime\.cn[/&:?=_]
.lotour\.net/analytics/statsv2\.js
.mafengwo\.cn/uva/i\.gif\?
.mixer\.sina\.cn[/&:?=_]
.mlog\.aipai\.com[/&:?=_]
.msg\.ettoday\.net[/&:?=_]
.msg\.iqiyi\.com[/&:?=_]
.msg\.video\.qiyi\.com[/&:?=_]
.msn\.ynet\.com/c/tj_comm\.js
.news\.cn/pc-log\?
.newspage\.xilu\.com/model/visitlog\.js
.nmgnews\.com\.cn/sys/online_calc\.js
.nsclick\.baidu\.com[/&:?=_]
.olpv\.onlylady\.com[/&:?=_]
.other\.v\.duowan\.com[/&:?=_]
.p0y\.cn[/&:?=_]
.p2p\.v\.yyclouds\.com/crossdomain\.xml
.pconline\.com\.cn/count\.php\?
.pcpop\.com/pv/pv\.js
.playstats\.v\.duowan\.com[/&:?=_]
.push\.zhanzhang\.baidu\.com/push\.js
.pv\.ltn\.com\.tw[/&:?=_]
.pv\.zhiding\.cn[/&:?=_]
.pvtest\.zol\.com\.cn[/&:?=_]
.qdp\.qidian\.com[/&:?=_]
.qhimg\.com/clk\.gif\?
.qhimg\.com/js/iwt\.js
.qunar\.com/js/ga\.min\.js
.qunar\.com/render/ga\.jsp\?
.qunar\.com/render/googlesem\.jsp
.qyer\.com[/&:?=_].*/base_beacon_ga\.js
.qzwb\.com/phpstat/
.record\.kuai\.xunlei\.com[/&:?=_]
.reportlog\.dftoutiao\.com[/&:?=_]
.runsky\.com/phpstat/
.s-msn\.com/portal/js/vendor/manto/
.s\.btime\.com[/&:?=_]
.s\.so\.360\.cn[/&:?=_]
.s\.union\.360\.cn[/&:?=_]
.sina\.cn.*/view\?
.sogou\.com/cl\.gif\?
.sohu\.com/mail/pv/
.stat\.2u\.com\.cn/ol_2u\.js
.stat\.baike\.com[/&:?=_]
.stat\.cnmo\.com[/&:?=_]
.stat\.cqwb\.com\.cn[/&:?=_]
.stat\.cutv\.com[/&:?=_]
.stat\.download\.xunlei\.com[/&:?=_]
.stat\.ea3w\.com[/&:?=_]
.stat\.game\.yy\.com[/&:?=_]
.stat\.hebnews\.cn[/&:?=_]
.stat\.hkwb\.net[/&:?=_]
.stat\.house365\.com[/&:?=_]
.stat\.ijinshan\.com[/&:?=_]
.stat\.img-space\.com[/&:?=_]
.stat\.mql5\.com[/&:?=_]
.stat\.pchome\.net[/&:?=_]
.stat\.timedg\.com[/&:?=_]
.stat\.ts\.cn[/&:?=_]
.stat\.v\.17173\.com[/&:?=_]
.stat\.xgo\.com\.cn[/&:?=_]
.stat\.yunfan\.com[/&:?=_]
.static\.gridsumdissector\.com[/&:?=_]
.static\.youku\.com/.*/index/js/iresearch\.js
.static\.youku\.com/.*/js/cps\.js
.static\.zongheng\.com[/&:?=_].*/ad_click\.js
.static\.zongheng\.com[/&:?=_].*/adClickStat\.js
.static\.zongheng\.com[/&:?=_].*/logger\.min\.js
.statis1\.mama\.cn[/&:?=_]
.stats\.766\.com[/&:?=_]
.stats\.v\.duowan\.com[/&:?=_]
.suning\.cn/javascript/sn_da/sa\.js
.sxrb\.com/front/stat/
.tajs\.qq\.com[/&:?=_]
.tcss\.qq\.com[/&:?=_]
.tj\.21ic\.com[/&:?=_]
.tjj\.com[/&:?=_]
.tongji\.xinmin\.cn[/&:?=_]
.track\.hujiang\.com[/&:?=_]
.track\.uc\.cn[/&:?=_]
.trends\.com\.cn/k\.js
.uuu9\.com/photolog\.html
.vm\.aty\.sohu\.com[/&:?=_]
.wanmei\.com/public/js/stat\.js
.wlxww\.com/html/analytics/
.xgo\.com\.cn/pv\.js
.xls\.go\.sohu\.com[/&:?=_]
.xs8\.cn/qreport\?
.xunlei\.com/api/stat/rt/js\?
.yaolan\.com/ylk\.mini\.js
.ynet\.com/c/js/manto\.min\.js
.youdao\.com/ctlog\?
.youdao\.com/rlog\.php
.youdao\.com/tl\?
.ysont\.cn[/&:?=_]
.zdnet\.com\.cn/js/pv\.js
.zdw\.w8\.com\.cn/p\.ht\?
.zhulang\.com/zlpv\.php
.zol\.com\.cn/cgimp/zc\.js
/__utm\.gif
/log\.gif\?
/track\.gif\?
.beacon\.sina\.com\.cn[/&:?=_]
.duba\.com/proxy/tj/
.google-analytics\.com/analytics\.js
.msg\.71\.am[/&:?=_]
.rs\.sinajs\.cn[/&:?=_]
.s\.360\.cn[/&:?=_]
.sinajs\.cn/open/analytics/
.stadig\.ifeng\.com[/&:?=_]
{ +filter{cjx-annoyance} }
*
{ -block }
.th7\.cn/sanda2015/css/ads\.js
.lancdn\.com/landian/public/js/ads\.js
{ -block +handle-as-image }
